version: '3'
services:
        echo:
                build: echo
                restart: always
#                ports:
#                        - "1323:1323"
                volumes:
                        - /etc/localtime:/etc/localtime:ro
                        - usock:/usock
                        - ./volumes/go_app:/go/src/app
                        - ./volumes/web-vol:/web
#                        - go_app:/go/src/app
#                        - web-vol:/web
                links:
                        - mysql
                environment:
                        - MYSQL_PASSWORD

        nginx:
                build: nginx
                ports:
                        - "443:443"
                        - "80:80"
#                links:
#                        - echo
                restart: always
                volumes:
                        - /etc/localtime:/etc/localtime:ro
                        - usock:/usock
                        - ./volumes/nginx/web-vol:/web
                        - ./volumes/nginx/web-root:/web-root
                        - ./volumes/nginx/acme:/acme
                        - /etc/letsencrypt:/etc/letsencrypt
                        - ./volumes/nginx-logs/nginx:/var/log/nginx
                        - ./volumes/nginx-logs/echo:/root/logs/

        mysql:
                build: mysql
#                ports:
#                        - "3306:3306"
                restart: always
                volumes:
                        - usock:/var/run/mysqld/
                        - ./volumes/db_data:/var/lib/mysql
#                        - db_data:/var/lib/mysql
                environment:
                        - TZ=Asia/Tokyo
                        - MYSQL_PASSWORD
                        - MYSQL_ROOT_PASSWORD

        cron:
                build: cron
                restart: always
                depends_on: nginx
                volumes:
                        - usock:/usock
                        - /etc/localtime:/etc/localtime:ro
                        - /etc/letsencrypt:/etc/letsencrypt
                        - ./volumes/nginx/acme:/acme
                        - ./volumes/db_backup:/db_backup
                environment:
                        - TZ=Asia/Tokyo
                        - MYSQL_PASSWORD


volumes:
        usock:
#                external: true # external が true なのでこの名前のボリュームが用意されてないと無いとエラー
#        web-vol:
#                external: true # external が true なのでこの名前のボリュームが用意されてないと無いとエラー
#        go_app:
#                external: true
#        db_data:
#                external: true

