version: '3'
services:
        echo:
                build: echo
                restart: always
                volumes:
                        - /etc/localtime:/etc/localtime:ro
                        - usock:/usock
                        - ./volumes/go_app:/go/src/app
                        - ./volumes/web-vol:/web
#                        - go_app:/go/src/app
#                        - web-vol:/web
                links:
                        - mysql

        nginx:
                build: nginx
                ports:
                        - "443:443"
                        - "80:80"
#                links:
#                        - echo
                restart: always
                volumes:
                        - /etc/localtime:/etc/localtime:ro
                        - usock:/usock
                        - ./volumes/web-vol:/web
#                        - web-vol:/web

        mysql:
                build: mysql
#                ports:
#                        - "3306:3306"
                restart: always
                volumes:
                        - usock:/var/run/mysqld/
                        - ./volumes/db_data:/var/lib/mysql
#                        - db_data:/var/lib/mysql
                environment:
                        TZ: Asia/Tokyo

        cron:
                build: cron
                restart: always
                volumes:
                        - usock:/usock
                        - /etc/localtime:/etc/localtime:ro
                environment:
                        TZ: Asia/Tokyo


volumes:
        usock:
#                external: true # external が true なのでこの名前のボリュームが用意されてないと無いとエラー
#        web-vol:
#                external: true # external が true なのでこの名前のボリュームが用意されてないと無いとエラー
#        go_app:
#                external: true
#        db_data:
#                external: true

